USE [master]
GO

/****** Object:  Database [appget]    Script Date: 11/22/2020 11:40:44 PM ******/
CREATE DATABASE [appget]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'appget', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\appget.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'appget_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\appget_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [appget].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [appget] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [appget] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [appget] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [appget] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [appget] SET ARITHABORT OFF 
GO

ALTER DATABASE [appget] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [appget] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [appget] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [appget] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [appget] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [appget] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [appget] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [appget] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [appget] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [appget] SET  ENABLE_BROKER 
GO

ALTER DATABASE [appget] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [appget] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [appget] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [appget] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [appget] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [appget] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [appget] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [appget] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [appget] SET  MULTI_USER 
GO

ALTER DATABASE [appget] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [appget] SET DB_CHAINING OFF 
GO

ALTER DATABASE [appget] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [appget] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [appget] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [appget] SET  READ_WRITE 
GO

